<a class=n target=content onClick="h(this);" href=cds.php><?=$TEXT['navi-cdcol']?></a><br>
<a class=n target=content onClick="h(this);" href=biorhythm.php><?=$TEXT['navi-bio']?></a><br>
<a class=n target=content onClick="h(this);" href=iart.php><?=$TEXT['navi-iart']?></a><br>
<a class=n target=content onClick="h(this);" href=ming.php><?=$TEXT['navi-iart2']?></a><br>
<a class=n target=content onClick="h(this);" href=phonebook.php><?=$TEXT['navi-phonebook']?></a><br>
<a class=n target=content onClick="h(this);" href=pear.php><?=$TEXT['navi-pear']?></a><br>
<a class=n target=content onClick="h(this);" href=adodb.php><?=$TEXT['navi-adodb']?></a>
